---
title: 'A Bayesian approach to analyzing urinary biomarkers for pancreatic cancer'
author: "Noora Torpo, Joel Himanen"
date: "11/25/2021"
output: pdf_document
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1)  Introduction describing the motivation, the problem and the main modeling idea. Showing some illustrative figure is recommended. (J)
2)  Description of the data and the analysis problem. Provide information where the data was obtained, and if it has been previously used in some online case study and how your analysis differs from the existing analyses. (J)
3)  Description of at least two models, for example: non hierarchical and hierarchical, linear and non linear, variable selection with many models. Pooled (J); Hierarchical (N)
4)  Informative or weakly informative priors, and justification of their choices. (N)
5)  Stan, rstanarm or brms code.
6)  How the Stan model was run, that is, what options were used. This is also more clear as combination of textual explanation and the actual code line. (J)
7)  Convergence diagnostics (Rˆ, ESS, divergences) and what was done if the convergence was not good with the first try. (J)
8)  Posterior predictive checks and what was done to improve the model. (N)
9)  Model comparison (e.g. with LOO-CV). (J)
10) Predictive performance assessment if applicable (e.g. classification accuracy) and evaluation of practical usefulness of the accuracy. If not applicable, then explanation why in this case the predictive performance is not applicable. (N)
11) Sensitivity analysis with respect to prior choices (i.e. checking whether the result changes a lot if prior is changed) (N)
12) Discussion of issues and potential improvements.
13) Conclusion what was learned from the data analysis.
14) Self-reflection of what the group learned while making the project.

# 1 Introduction

Pancreatic cancer, or more accurately, its most common form, *Pancreatic ductal adenocarcinoma* (PDAC), is one of the most lethal forms of cancer. It is often diagnosed at a very late stage, which, combined to its heterogenous base of genetic mutations, leads to an average 5-year survival rate of less than 10%. (Sarantis, et. al. 2020) Therefore, research on early signs of PDAC can be considered to be of utmost importance.

This study focuses on conducting Bayesian inference on a data set, which holds measurements of potential biomarkers for PDAC. We aim to model the biomarker levels using weakly informative priors to generate posterior distributions using two different approaches in Stan and R. The goal is to see if and how the distributions for the different biomarkers differ between healthy and positively diagnosed test subjects.

# 2 The data


# 3 Models

In this problem setting, we are fitting two types of models for the data: a pooled model and a hierarchical model. The goal is to find distributions for proteins for all three diagnosis groups. Therefore, the input data includes three matrices including the data as well as the numebr of observations. Note that the groups have different lengths. The data is denoted by $y_i$, $i=1,2,3$ corresponding to each group, where each column of presents four different proteins. Similarly the number of observations is denote as $n_i$. For the pooled model, we are using same parameters for all of the groups meaning that we are note considering the groups but the whole data set. For hierarchical model, the distributions have shared hyperparameters but for different groups, the distributions are fitted separately. 

As mentioned above, we are considering four proteins or biomarkers: creatinine, LYVE1, REG1B and TFF1. In both pooled and hierarchical model, the distributions are fitted separately for each protein. After considering the distributions of the data, we decided to fit an exponential model with two parameters to creatinine and after logarithmic transformation we decided to fit a Gaussian model to the three remaining proteins. In practice, this means that we are fitting gamma distribution to creatinine data and normal distribution to log-transformed data of LYVE1, REG1B and TFF1. Note that we are using natural logarithm. After logarithmic transformation, the histograms of the three proteins were similar enough for us to use same prior distributions for their parameters. The decision on on the usage of the log-scale and normal distribution was made after it turned out that the exponential model could not be fitted to the data sensibly.

TÄHÄN LISÄTÄÄN VIELÄ PAREMMAT PERUSTELUT EKSPONENTIALISEN JA NORMAALIMALLIN VALINNASTA, KUN TIETÄÄ MITÄ KAKKOS KOHTAAN ON KIRJOITETTU DATASTA JA MIHIN KUVIIN VAIKKA VIITATA.

## Pooled model

Exponential model fitted to the creatinine data can be written as follows. Note that the choice of priors will be discussed in part 4. The first column of the data is denoted as $y_i^1$. Gamma distribution is denoted as $\Gamma$.

$$
\begin{aligned}
y_i^1 &\sim \Gamma(\alpha, \beta) \hspace{1cm} i=1,2,3 \\
\alpha &\sim \Gamma(1,1) \\
\beta &\sim \Gamma(0.5,1)
\end{aligned}
$$

The Gaussian model fitted to the data for three other proteins can be written as follows. Indexing $j=2,3,4$ refers to the proteins LYVE1, REB1B and TFF1 respectively.

$$
\begin{aligned}
ln(y_i^j) &\sim \mathcal{N}\left(\mu^j, {\sigma^j}^2\right) \hspace{1cm} i=1,2,3 \hspace{5mm} j=2,3,4 \\
\mu^j &\sim \mathcal{N}\left(0,20^2\right)  \\
\sigma^j &\sim \Gamma(1,1)  \\
\end{aligned}
$$
## Hierarchical model

Hierarchical model is constricted similarly but defined priors use hyperparametrs. In general, we will denote hyperparameters with lower index P. The corresponding hierarchical formulation of the exponential model to the creatinine data can be written as follows.

$$
\begin{aligned}
y_i^1 &\sim \Gamma(\alpha_i, \beta_i) \hspace{1cm} i=1,2,3 \\
\alpha_i &\sim \Gamma(\alpha_{P_1},\beta_{P_1}) \\
\beta_i &\sim \Gamma(\alpha_{P_1},\beta_{P_1}) \\
\alpha_{P_k} &\sim \Gamma(1,1) \hspace{1cm} k=1,2 \\
\beta_{P_k} &\sim \Gamma(1,1)
\end{aligned}
$$
The corresponding hierarchical formulation of the Gaussian model fitted to the data for three other proteins can be written as follows.

$$
\begin{aligned}
ln(y_i^j) &\sim \mathcal{N}\left(\mu^j_i, {\sigma^j_i}^2\right) \hspace{1cm} &i=1,2,3 \hspace{5mm} j=2,3,4 \\
\mu^j_i &\sim \mathcal{N}\left(\mu_{P_1}^j,{\sigma_{P_1}^j}^2\right)   \\
\sigma^j_i &\sim \Gamma\left(\mu_{P_2}^j,\sigma_{P_2}^j\right) \\
\mu_{P_1}^j &\sim \mathcal{N}\left(0,20^2\right) \\
\mu_{P_2}^j &\sim \Gamma(1,1) \\
\sigma_{P_k}^j &\sim \Gamma(1,1) & k=1,2
\end{aligned}
$$

# 4 Priors

# References

[1] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7031151/
